linear_axis_base_link:
  origin: {x: 0.0, y: 0.0, z: 0.0, roll: 0.0, pitch: 0.0, yaw: 0.0}
  geometry:
    box: {x: 0.12, y: 0.12, z: 0.564}

linear_axis_middle_link:
  origin: {x: 0.0, y: 0.0, z: 0.0, roll: 0.0, pitch: 0.0, yaw: 0.0}
  geometry:
    box: {x: 0.10, y: 0.10, z: 0.30}

linear_axis_upper_link:
  origin: {x: 0.0, y: 0.0, z: 0.0, roll: 0.0, pitch: 0.0, yaw: 0.0}
  geometry:
    box: {x: 0.08, y: 0.08, z: 0.30}

linear_axis_top_plate_link:
  origin: {x: 0.0, y: 0.0, z: 0.0, roll: 0.0, pitch: 0.0, yaw: 0.0}
  geometry:
    box: {x: 0.12, y: 0.12, z: 0.02}

chest_link0:
  origin:
    x: 0.105
    y: 0.0
    z: -0.693
    roll: 1.5707963267948966
    pitch: 0.0
    yaw: 1.5707963267948966
  geometry:
    mesh: "package://openarm_description/assets/robot/openarm_v2.0/meshes/body/collision/chest_link0_symp.stl"
    scale: {x: 0.001, y: 0.001, z: 0.001}
