linear_axis_foot_link:
  origin: {x: 0.0, y: 0.0, z: 0.0, roll: 0.0, pitch: 0.0, yaw: 0.0}
  geometry:
    box: {x: 0.176, y: 0.0955, z: 0.046}
  material:
    rgba: "0.18 0.18 0.18 1.0"

linear_axis_base_link:
  origin: {x: 0.0, y: 0.0, z: 0.0, roll: 0.0, pitch: 0.0, yaw: 0.0}
  geometry:
    box: {x: 0.05, y: 0.08, z: 0.524}
  material:
    rgba: "0.18 0.18 0.18 1.0"

linear_axis_middle_link:
  origin: {x: 0.0, y: 0.0, z: 0.0, roll: 0.0, pitch: 0.0, yaw: 0.0}
  geometry:
    box: {x: 0.04, y: 0.07, z: 0.30}
  material:
    rgba: "0.28 0.28 0.28 1.0"

linear_axis_upper_link:
  origin: {x: 0.0, y: 0.0, z: 0.0, roll: 0.0, pitch: 0.0, yaw: 0.0}
  geometry:
    box: {x: 0.04, y: 0.07, z: 0.30}
  material:
    rgba: "0.38 0.38 0.38 1.0"

linear_axis_top_plate_link:
  origin: {x: 0.0, y: 0.0, z: 0.0, roll: 0.0, pitch: 0.0, yaw: 0.0}
  geometry:
    box: {x: 0.06, y: 0.06, z: 0.15}
  material:
    rgba: "0.22 0.22 0.22 1.0"

chest_link0:
  origin:
    x: 0.105
    y: 0.0
    z: -0.693
    roll: 1.5707963267948966
    pitch: 0.0
    yaw: 1.5707963267948966
  geometry:
    mesh: "package://openarm_description/assets/robot/openarm_v2.0/meshes/body/visual/chest_link0.dae"
    scale: {x: 1.0, y: 1.0, z: 1.0}
