chest_link0:
  origin: {x: 0.105, y: 0.0, z: -0.693, roll: 1.5707963267948966, pitch: 0.0, yaw: 1.5707963267948966}
  geometry:
    mesh: "package://openarm_description/assets/robot/openarm_v2.0/meshes/body/visual/chest_link0.dae"
    scale: {x: 1.0, y: 1.0, z: 1.0}
