left_arm_mount_point:
  parent: chest_link0
  origin:
    x: 0.01
    y: 0.031
    z: 0.005
    roll: 0.0
    pitch: 0.0
    yaw: 0.0

right_arm_mount_point:
  parent: chest_link0
  origin:
    x: 0.01
    y: -0.031
    z: 0.005
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
