links:
  - body_link0
  - linear_axis_base_link
  - linear_axis_middle_link
  - linear_axis_upper_link
  - linear_axis_top_plate_link
  - chest_link0

joints:
  body_linear_axis_base_joint:
    type: fixed
    parent: body_link0
    child: linear_axis_base_link
    origin: {x: 0.0, y: 0.0, z: 0.282, roll: 0.0, pitch: 0.0, yaw: 0.0}

  linear_axis_joint:
    type: prismatic
    parent: linear_axis_base_link
    child: linear_axis_upper_link
    origin: {x: 0.0, y: 0.0, z: 0.132, roll: 0.0, pitch: 0.0, yaw: 0.0}
    axis: {x: 0.0, y: 0.0, z: 1.0}
    limit:
      lower: 0.0
      upper: 0.6
      effort: 10000.0
      velocity: 0.1
    dynamics:
      damping: 50.0
      friction: 0.0

  linear_axis_middle_joint:
    type: prismatic
    parent: linear_axis_base_link
    child: linear_axis_middle_link
    origin: {x: 0.0, y: 0.0, z: 0.132, roll: 0.0, pitch: 0.0, yaw: 0.0}
    axis: {x: 0.0, y: 0.0, z: 1.0}
    limit:
      lower: 0.0
      upper: 0.3
      effort: 10000.0
      velocity: 0.05
    mimic:
      joint: linear_axis_joint
      multiplier: 0.5
      offset: 0.0
    dynamics:
      damping: 25.0
      friction: 0.0

  linear_axis_upper_top_plate_joint:
    type: fixed
    parent: linear_axis_upper_link
    child: linear_axis_top_plate_link
    origin: {x: 0.0, y: 0.0, z: 0.16, roll: 0.0, pitch: 0.0, yaw: 0.0}

  linear_axis_top_plate_chest_joint:
    type: fixed
    parent: linear_axis_top_plate_link
    child: chest_link0
    origin: {x: -0.01, y: 0.0, z: 0.09, roll: 0.0, pitch: 0.0, yaw: 0.0}
