linear_axis_foot_link:
  origin: {x: 0.0, y: 0.0, z: 0.0, roll: 0.0, pitch: 0.0, yaw: 0.0}
  mass: 10.0
  inertia: {xx: 0.009364, xy: 0.0, xz: 0.0, yy: 0.027577, yz: 0.0, zz: 0.033414}

linear_axis_base_link:
  origin: {x: 0.0, y: 0.0, z: 0.0, roll: 0.0, pitch: 0.0, yaw: 0.0}
  mass: 10.0
  inertia: {xx: 0.234147, xy: 0.0, xz: 0.0, yy: 0.230897, yz: 0.0, zz: 0.007417}

linear_axis_middle_link:
  origin: {x: 0.0, y: 0.0, z: 0.0, roll: 0.0, pitch: 0.0, yaw: 0.0}
  mass: 5.0
  inertia: {xx: 0.039542, xy: 0.0, xz: 0.0, yy: 0.038167, yz: 0.0, zz: 0.002708}

linear_axis_upper_link:
  origin: {x: 0.0, y: 0.0, z: 0.0, roll: 0.0, pitch: 0.0, yaw: 0.0}
  mass: 4.0
  inertia: {xx: 0.031633, xy: 0.0, xz: 0.0, yy: 0.030533, yz: 0.0, zz: 0.002167}

linear_axis_top_plate_link:
  origin: {x: 0.0, y: 0.0, z: 0.0, roll: 0.0, pitch: 0.0, yaw: 0.0}
  mass: 0.5
  inertia: {xx: 0.001088, xy: 0.0, xz: 0.0, yy: 0.001088, yz: 0.0, zz: 0.000300}

chest_link0:
  origin: {x: 0.01, y: 0.0, z: 0.005, roll: 0.0, pitch: 0.0, yaw: 0.0}
  mass: 13.89
  inertia: {xx: 1.653, xy: 0.0, xz: 0.0, yy: 1.653, yz: 0.0, zz: 0.051}
